version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - ./:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7.19
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:cached