version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - ./:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: dbserver
    platform: linux/x86_64
    env_file: .env
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:cached