// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type EditTodo struct {
	TodoID      uint    `json:"todoId"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
}
