// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Category string

const (
	CategoryToday    Category = "TODAY"
	CategoryTomorrow Category = "TOMORROW"
	CategoryEver     Category = "EVER"
)

var AllCategory = []Category{
	CategoryToday,
	CategoryTomorrow,
	CategoryEver,
}

func (e Category) IsValid() bool {
	switch e {
	case CategoryToday, CategoryTomorrow, CategoryEver:
		return true
	}
	return false
}

func (e Category) String() string {
	return string(e)
}

func (e *Category) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Category(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Category", str)
	}
	return nil
}

func (e Category) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
